### ISSUE TITLE
Servo only one postition even low or raise. Can't raise during printing (On CNC machine, with sg90 servo).

### ISSUE THREAD

**Issue by caogia** [bullestock/4xidraw#4]
hi, I uploaded grbl servo sketch to my uno CNC machine, It worked well
The servo can turn but only one position, doesn't seem to raise up.
my servo is china sg90 toy servo, it work well with arduino servo sample sketch but can't work properly on axidraw.
Please help.

**Comment by madc** [comment]
I had to switch the values for `Pen UP` and `Pen Down` in `4xiDraw Control` > `Setup`. Hope that helps..

![4xiDraw_control](https://user-images.githubusercontent.com/343392/68477399-b31c9480-022d-11ea-860f-2f65b5c15b2f.png)

**Comment by bullestock** [comment]
> I had to switch the values for `Pen UP` and `Pen Down` in `4xiDraw Control` > `Setup`. Hope that helps..

That probably means that your servo is rotated 180 degrees with respect to mine.
